"""
pr_agent.py — Stage 5: Open a draft PR and notify on the original issue.

HARD RULE: This agent NEVER calls the merge API. Draft PRs only.
"""

from __future__ import annotations
import textwrap

from schemas.implement_output import ImplementOutput
from schemas.plan_output import PlanOutput
from schemas.test_output import TestOutput
from utils.github_client import GitHubClient
from utils.logger import log_stage_start, log_stage_end

_AI_LABEL = "ai-generated"
_AI_LABEL_COLOR = "7057ff"  # Purple


def run(
    gh: GitHubClient,
    issue_number: int,
    plan: PlanOutput,
    implement_output: ImplementOutput,
    test_output: TestOutput,
    diff_size_threshold: int,
    sensitive_paths_touched: list[str],
    senior_reviewer: str,
) -> int:
    """
    Open a draft PR and post a summary comment on the issue.
    Returns the PR number.
    """
    log_stage_start(
        stage="pr",
        issue_number=issue_number,
        attempt=0,
        inputs={
            "branch": implement_output.branch_name,
            "diff_lines": implement_output.diff_size_lines,
        },
    )

    # 1. Build PR body
    pr_body = _build_pr_body(issue_number, plan, implement_output, test_output)

    # 2. Create draft PR
    pr = gh.create_draft_pr(
        title=f"feat(ai): implement issue #{issue_number}",
        body=pr_body,
        head_branch=implement_output.branch_name,
        base_branch="main",
    )
    pr_number = pr["number"]
    pr_url = pr["html_url"]

    # 3. Apply ai-generated label
    gh.ensure_label(_AI_LABEL, _AI_LABEL_COLOR)
    gh.add_labels_to_pr(pr_number, [_AI_LABEL])

    # 4. Request senior review if diff is large OR sensitive paths touched
    needs_senior_review = (
        implement_output.diff_size_lines > diff_size_threshold
        or bool(sensitive_paths_touched)
    )
    if needs_senior_review and senior_reviewer:
        gh.request_pr_reviewers(pr_number, [senior_reviewer])

    # 5. Post summary comment on the original issue
    issue_comment = _build_issue_comment(pr_url, implement_output, test_output)
    gh.post_issue_comment(issue_number, issue_comment)

    log_stage_end(
        stage="pr",
        issue_number=issue_number,
        attempt=0,
        outputs={"pr_number": pr_number, "pr_url": pr_url},
    )

    return pr_number


# ── Templates ─────────────────────────────────────────────────────────────────

def _build_pr_body(
    issue_number: int,
    plan: PlanOutput,
    implement: ImplementOutput,
    test: TestOutput,
) -> str:
    steps_md = "\n".join(
        f"- **{s.action.upper()}** `{s.file}`: {s.description}"
        for s in plan.steps
    )
    tests_md = "\n".join(f"- `{t}`" for t in plan.tests_to_write) or "*(see existing test class)*"
    deviations_md = (
        "\n".join(f"- {d}" for d in implement.deviations_from_plan)
        or "None — implementation followed the plan exactly."
    )
    test_status = "✅ All tests passed" if test.passed else f"⚠️ {test.tests_failed} test(s) failed"

    return textwrap.dedent(f"""
    > ⚠️ **This PR was generated by an AI agent.** It requires human review before merging.
    > Do NOT merge without carefully reviewing the diff.

    ## Resolves #{issue_number}

    ---

    ## Implementation Plan

    {plan.plan_narrative}

    ### Changes
    {steps_md}

    ### Tests written/updated
    {tests_md}

    ### Edge cases handled
    {chr(10).join(f'- {e}' for e in plan.edge_cases) or '*(see code comments)*'}

    ---

    ## Test Results

    **Status:** {test_status}
    **Tests run:** {test.tests_run} | **Failed:** {test.tests_failed}
    **Full log:** {test.full_log_url}

    {f'**Failure summary:** {test.failure_summary}' if test.failure_summary else ''}

    ---

    ## Deviations from Plan

    {deviations_md}

    ---

    ## Diff summary

    {implement.diff_summary}

    **Files changed:** {', '.join(f'`{f}`' for f in implement.files_changed)}
    **Approximate size:** {implement.diff_size_lines} lines

    ---

    *Generated by the issue-implement-bot pipeline. Commit: `{implement.commit_sha[:8]}`*
    """).strip()


def _build_issue_comment(
    pr_url: str,
    implement: ImplementOutput,
    test: TestOutput,
) -> str:
    test_status = "✅ passing" if test.passed else f"⚠️ {test.tests_failed} failure(s)"
    return textwrap.dedent(f"""
    🤖 **AI Implementation Ready for Review**

    I've analyzed this issue, created an implementation plan, written the code,
    and verified it against the test suite.

    **Draft PR:** {pr_url}
    **Branch:** `{implement.branch_name}`
    **Tests:** {test_status}
    **Changes:** {implement.diff_summary[:200]}

    A human must review and approve the PR before anything can merge.
    The PR is marked as a **draft** — no one can accidentally merge it.

    If you'd like the AI to revise the implementation based on your review,
    comment `/retry <your feedback>` on the PR and I'll re-enter the pipeline
    with your feedback as context.
    """).strip()
